# ld-linux has a bunch of copies of libc functions
# (since it can't call libc before loading it),
# so just load them from there.
# Given there's even been some mentions over on the glibc mailing list of potentially planning to make the libc.so a stub and put everything in ld-linux,
# this might even also be useful for future-proofing :p
import "libc.so";
